name: salon_vishu
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.6.3
  google_sign_in: ^5.4.3
  sign_in_with_apple: ^4.3.0
  cloud_firestore: ^4.3.1
  hexcolor: ^3.0.1
  flutter_date_pickers: ^0.4.2
  provider: ^6.0.5
  image_picker: ^0.8.6
  intl: ^0.18.0
  firebase_storage: ^11.0.8
  package_info_plus: ^4.0.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.7
  table_calendar: ^3.0.8
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  cloud_functions: ^4.0.7
  http: ^0.13.5
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  dio: ^5.0.0



flutter_native_splash:
  image: images/vishu_logo.png
  color: "#613822"
  android_12:
    image: images/vishu_android_image.png
    color: "#613822"


flutter_icons:
  android: true
  ios: true
  image_path_ios: "images/vishu_logo.png"
  image_path_android: "images/vishu_android_image.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "images/vishu_android_image.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Dancing_Script
      fonts:
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Bold.ttf
          weight: 100
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Medium.ttf
          weight: 100
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Regular.ttf
          weight: 100
        - asset: assets/fonts/Dancing_Script/static/DancingScript-SemiBold.ttf
          weight: 100
        - asset: assets/fonts/Dancing_Script/DancingScript-VariableFont_wght.ttf
          weight: 900

    - family: shokaki_sarari
      fonts:
          - asset: assets/fonts/shokaki_sarari/しょかきさらり行体.ttf
            weight: 100
          - asset: assets/fonts/shokaki_sarari/しょかきさらり行体.ttf
            weight: 100
          - asset: assets/fonts/shokaki_sarari/しょかきさらり行体.ttf
            weight: 100
          - asset: assets/fonts/shokaki_sarari/しょかきさらり行体.ttf
            weight: 100
          - asset: assets/fonts/shokaki_sarari/しょかきさらり行体.ttf
            weight: 900


  uses-material-design: true


  assets:
    - images/begin_cancel.jpg
    - images/complete_cancel.PNG
    - images/vishu_logo.png
    - images/vishu_android_image.png
    - images/first_sign_in_image.png
    - images/second_sign_in_image.png
    - images/third_sign_in_image.png
